
export const APPLY_POST_REQUEST='APPLY_POST_REQUEST'
export const APPLY_POST_SUCCESS='APPLY_POST_SUCCESS'
export const APPLY_POST_FAILURE='APPLY_POST_FAILURE'

export const DELETE_APPLICATION_REQUEST='DELETE_APPLICATION_REQUEST'
export const DELETE_APPLICATION_SUCCESS='DELETE_APPLICATION_SUCCESS'
export const DELETE_APPLICATION_FAILURE='DELETE_APPLICATION_FAILURE'


