export const FETCH_FIELDS_SUCCESS = "FETCH_FIELDS_SUCCESS";
export const FETCH_FIELDS_REQUEST = "FETCH_FIELDS_REQUEST";
export const FETCH_FIELDS_FAILURE = "FETCH_FIELDS_FAILURE";

export const FETCH_FIELDS_FOR_CREATE_SUCCESS =
  "FETCH_FIELDS_FOR_CREATE_SUCCESS";
export const FETCH_FIELDS_FOR_CREATE_REQUEST =
  "FETCH_FIELDS_FOR_CREATE_REQUEST";
export const FETCH_FIELDS_FOR_CREATE_FAILURE =
  "FETCH_FIELDS_FOR_CREATE_FAILURE";
