
export const CREATE_EMPLOYER_REQUEST='CREATE_EMPLOYER_REQUEST'
export const CREATE_EMPLOYER_SUCCCESS='CREATE_EMPLOYER_SUCCESS'
export const CREATE_EMPLOYER_FAILURE='CREATE_EMPLOYER_FAILURE' 

export const CREATE_FIELD_REQUEST='CREATE_FIELD_REQUEST'
export const CREATE_FIELD_SUCCCESS='CREATE_FIELD_SUCCESS'
export const CREATE_FIELD_FAILURE='CREATE_FIELD_FAILURE' 

export const UPDATE_FIELD_REQUEST='UPDATE_FIELD_REQUEST'
export const UPDATE_FIELD_SUCCCESS='UPDATE_FIELD_SUCCESS'
export const UPDATE_FIELD_FAILURE='UPDATE_FIELD_FAILURE' 

export const UPDATE_EMPLOYER_REQUEST='UPDATE_EMPLOYER_REQUEST'
export const UPDATE_EMPLOYER_SUCCCESS='UPDATE_EMPLOYER_SUCCESS'
export const UPDATE_EMPLOYER_FAILURE='UPDATE_EMPLOYER_FAILURE' 

export const DELETE_EMPLOYER_REQUEST='DELETE_EMPLOYER_REQUEST'
export const DELETE_EMPLOYER_SUCCCESS='DELETE_EMPLOYER_SUCCESS'
export const DELETE_EMPLOYER_FAILURE='DELETE_EMPLOYER_FAILURE' 

export const GET_EMPLOYERS_REQUEST='GET_EMPLOYERS_REQUEST'
export const GET_EMPLOYERS_SUCCCESS='GET_EMPLOYERS_SUCCESS'
export const GET_EMPLOYERS_FAILURE='GET_EMPLOYERS_FAILURE' 

export const GET_FIELDS_REQUEST='GET_FIELDS_REQUEST'
export const GET_FIELDS_SUCCCESS='GET_FIELDS_SUCCESS'
export const GET_FIELDS_FAILURE='GET_FIELDS_FAILURE' 

export const GET_ALL_POSTS_REQUEST='GET_ALL_POSTS_REQUEST'
export const GET_ALL_POSTS_FAILURE='GET_ALL_POSTS_FAILURE'
export const GET_ALL_POSTS_SUCCESS='GET_ALL_POSTS_SUCCESS'